#ifndef BUSYBEAVER_ERRORS_H
#define BUSYBEAVER_ERRORS_H

#define BB_ERR_FOPEN -1
#define BB_ERR_FSEEK -2
#define BB_ERR_FTELL -3
#define BB_ERR_MALLOC -4
#define BB_ERR_FGETS -5
#define BB_ERR_BADFILE -6
#define BB_ERR_OTHER -100

#endif /* BUSYBEAVER_ERRORS_H */
